# © 2026 aiaiaiai · aiaiaiai.org
# SPDX-License-Identifier: MPL-2.0

[package]
name = "nilxone-bindings-wasm"
description = "WebAssembly translation boundary for 0x1 Core."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
nilxone-contracts = { version = "0.1.0", path = "../nilxone-contracts" }
nilxone-kernel = { version = "0.1.0", path = "../nilxone-kernel" }
wasm-bindgen = "=0.2.127"

[lints]
workspace = true
