# © 2026 aiaiaiai · aiaiaiai.org
# SPDX-License-Identifier: MPL-2.0

[package]
name = "nilxone-kernel"
description = "Deterministic transition kernel for 0x1 Core."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
nilxone-contracts = { version = "0.1.0", path = "../nilxone-contracts" }

[lints]
workspace = true
